### ISSUE TITLE
I have new GPU driver,but.....

### ISSUE THREAD

**Issue by albbzmkh** [pkhungurn/talking-head-anime-demo#12]
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\PYTHON\anaconda\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:/OneDrive/Python/aa/talking-head-anime-demo/app/puppeteer.py", line 94, in load_image
    self.load_image_from_file(file_name)
  File "D:/OneDrive/Python/aa/talking-head-anime-demo/app/puppeteer.py", line 106, in load_image_from_file
    self.source_image = extract_pytorch_image_from_filelike(file_name).to(self.torch_device).unsqueeze(dim=0)
  File "D:\PYTHON\anaconda\lib\site-packages\torch\cuda\__init__.py", line 196, in _lazy_init
    _check_driver()
  File "D:\PYTHON\anaconda\lib\site-packages\torch\cuda\__init__.py", line 101, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
[ WARN:0] terminating async callback

**Comment by dragonmeteor** [comment]
Sorry for the late reply.

First, let us confirm one thing. Do you have an Nvidia GPU? You said you have a new driver, but you didn't say you have such a GPU.

**Comment by sheiun** [comment]
@albbzmkh You need to make sure `torch.cuda.device_count()` is greater than `0`

**Comment by drojf** [comment]
@dragonmeteor you may want to explicitly add to the readme that you need a NVIDIA GPU/Cuda capable gpu to use this, as it's not stated there as a requirement.

**Comment by MISONLN41** [comment]
I have faced same issue. I installed cpu-only torch, but it returns `AssertionError: Torch not compiled with CUDA enabled`

**Comment by dragonmeteor** [comment]
I've updated the README to say that a GPU is required.

You can definitely run the code with only a CPU, but it is hopelessly slow.
