### ISSUE TITLE
Puppeteer Runtime Error

### ISSUE THREAD

**Issue by DearVa** [pkhungurn/talking-head-anime-demo#14]
This happened when I try to run "puppeteer.py", my camera worked perfectly and I could see my face was highlighted. However, when I import a image, it stopped working and showed this:
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:\Python\Python36\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "app/puppeteer.py", line 142, in update_image
    left_eye_normalized_ratio = compute_left_eye_normalized_ratio(face_landmarks, eye_min_ratio, eye_max_ratio)
  File "F:\Source\Python\talking-head-anime-demo\puppet\util.py", line 15, in compute_left_eye_normalized_ratio
    min_ratio, max_ratio)
  File "F:\Source\Python\talking-head-anime-demo\puppet\util.py", line 26, in compute_eye_normalized_ratio
    left_eye_horiz_diff = face_landmarks.part(eye_horiz_points[0]) - face_landmarks.part(eye_horiz_points[1])
TypeError: unsupported operand type(s) for -: 'point' and 'point'
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by DearVa** [comment]
I can run "manual_poser.py" perfectly and no exception was thrown.

**Comment by DearVa** [comment]
I have sloved it, thank you.

**Comment by callanrocks** [comment]
> I have sloved it, thank you.

Can yous share how?
