### ISSUE TITLE
Puppeteer Runtime Error

### ISSUE THREAD

**Issue by 1235467** [pkhungurn/talking-head-anime-demo#42]
It happened after run it about 30 seconds.The camera suddenly stuck.Moreover,importing a picture into it,the right side says "nothing yet"
```
PS G:\talking-head-anime-demo> python app/puppeteer.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Python39\lib\tkinter\__init__.py", line 806, in callit
    func(*args)
  File "G:\talking-head-anime-demo\app\puppeteer.py", line 119, in update_image
    self.draw_face_box(rgb_frame, face_box_points)
  File "G:\talking-head-anime-demo\app\puppeteer.py", line 175, in draw_face_box
    cv2.line(frame, face_box_points[start], face_box_points[end], (255, 0, 0), thickness=2)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
```

**Comment by dragonmeteor** [comment]
I've updated the code in the hopes that it would solve your problem. Please pull and see if this work or not.

**Comment by 1235467** [comment]
It works.Thank you for your help.

**Comment by pkhungurn** [comment]
Very nice to hear this. Thanks for reporting the issue.
