### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by reimurin** [pkhungurn/talking-head-anime-demo#7]
When I have all the dependencies installed, and ran the python app, it occurred the following errors:
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 804, in callit
    func(*args)
  File "app/manual_poser.py", line 112, in update_image
    posed_image = self.poser.pose(self.source_image, self.current_pose).detach().cpu()
  File "D:\Downloads\talking-head-anime-demo-master\poser\morph_rotate_combine_poser.py", line 82, in pose
    combined_image = combine_module(rotated_images[0], rotated_images[1], rotate_params)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Downloads\talking-head-anime-demo-master\tha\combiner.py", line 42, in forward
    y = self.main_body(x)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Downloads\talking-head-anime-demo-master\nn\u_net_module.py", line 61, in forward
    y = torch.cat([x, downward_outputs[i]], dim=1)
RuntimeError: error in LoadLibraryA
And the program cannot present any live2d pictures.
Can U take a look at it?

**Comment by dragonmeteor** [comment]
It seems that you are not able to run Pytorch on your machine because the system gets an error when it wants to load a library.

Let's check first if there's anything that prevents Pytorch from being run. For example, do you have an Nvidia GPU?

**Comment by reimurin** [comment]
Yes, I do have an Nvidia GPU.

**Comment by dragonmeteor** [comment]
In that case, let's try creating a new Python library from scratch with Anaconda, using the instruction of the README file.
